// Newer Studio copy that was added after the v1.7 Chinese translation.
// Keep this table small and literal: ko() uses it only when a call has no
// explicit Chinese third argument.
export const zhExtra = Object.freeze({
  "→ Viewport": "→ 视口",
  "↓ Timeline, Shots lane": "↓ 时间轴·镜头轨",
  "✓ A 카메라 기준 저장 · 카메라 잠금": "✓ 已保存 A 的摄影机基准 · 摄影机锁定",
  "✓ A/B 카메라 프레이밍 일치 확인 · 카메라 잠금": "✓ A/B 构图一致 · 摄影机锁定",
  "1. Select the shot": "1. 选择镜头",
  "2. Draw rail, then drag across the top view": "2. 画摄影机轨道，再在顶视图中拖动",
  "A GLB, OBJ or FBX model standing in the set": "放在场景中的 GLB、OBJ 或 FBX 模型",
  "A 이후 카메라가 바뀌었어요. A 카메라로 복원하세요.": "A 之后摄影机发生了变化，请恢复 A 的机位。",
  "A 재캡처": "重新捕捉 A",
  "A 카메라로 복원": "恢复 A 的机位",
  "A 캡처": "捕捉 A",
  "A 포즈 하나와 동작 설명으로 움직임을 만듭니다.": "根据 A 姿势和动作描述生成运动。",
  "A/B 참조는 View에서 부위 색상 → 음영을 켜야 캡처할 수 있어요.": "捕捉 A/B 参考前，请在“视图”中开启“身体部位颜色 → 明暗”。",
  "A/B 참조에 캐릭터 전신이 다 안 들어왔어요. 샷 시점에서 머리와 양발이 화면 안에 들어오도록 카메라를 뒤로 빼고 다시 캡처하세요.": "A/B 参考未拍到人物全身。请在镜头视角中后退摄影机，确保头和双脚都在画面内，再重新捕捉。",
  "A/B 참조에는 부위 색상 음영 모드가 필요합니다.": "A/B 参考需要开启身体部位颜色的明暗模式。",
  "A/B 캡처는 뷰포트에서 합니다. 닫고 카드에서 캡처하세요.": "A/B 捕捉在视口中进行。关闭此窗口后从卡片捕捉。",
  "A→B 보간 생성": "生成 A→B 过渡",
  "A→B 보간": "A→B 过渡",
  "Add a shot first — a pack describes one cut": "请先添加镜头；一个参考包对应一个剪辑段。",
  "Add a shot first — a storyboard is one row per shot": "请先添加镜头；故事板每个镜头占一格。",
  "Add a shot to export OTIO": "添加镜头后才能导出 OTIO。",
  "Add a shot to export video or OTIO": "添加镜头后才能导出视频或 OTIO。",
  "Agent panel": "智能助手面板",
  "Agent": "智能助手",
  "Alt + left-drag to circle": "按住 Alt 并左键拖动以环绕",
  "Arrange characters": "安排人物",
  "Arrange objects": "布置物件",
  "Ask the agent to block, frame or animate…": "让智能助手摆场景、定构图或做动画…",
  "A를 먼저 캡처하면 카메라 기준을 저장합니다.": "先捕捉 A，即可保存摄影机基准。",
  "A만 동작 모드에서는 B를 제거하세요.": "仅用 A 生成动作时，请移除 B。",
  "A만 동작": "仅用 A 生成动作",
  "A만 캡처한 뒤 동작을 적으세요. 예: 검을 머리 위로 휘두르고 한 걸음 전진": "只捕捉 A 后描述动作。例如：举剑过头顶，再向前一步。",
  "A에서 B로 어떻게 움직이는지 적으세요. 예: 벤치로 걸어가 돌아서 앉는다": "描述从 A 到 B 的动作。例如：走向长椅、转身并坐下。",
  "A와 B 사이를 어떻게 움직일지 설명과 함께 만듭니다.": "结合动作描述生成 A 到 B 的过渡。",
  "A와 B 사이에서 카메라가 바뀌었어요. 같은 카메라로 다시 캡처하세요.": "A 和 B 之间摄影机发生变化，请用同一机位重新捕捉。",
  "A와 B 사이에서 카메라가 이동했어요. 같은 카메라 프레이밍으로 다시 캡처하세요.": "A 和 B 之间摄影机移动了，请保持相同构图重新捕捉。",
  "A와 B 포즈를 먼저 캡처하세요.": "请先捕捉 A 和 B 姿势。",
  "B 재캡처": "重新捕捉 B",
  "B 제거": "移除 B",
  "B 캡처": "捕捉 B",
  "B 포즈를 만든 뒤 카메라를 움직이지 말고 B 캡처를 누르세요": "摆好 B 姿势后保持摄影机不动，再点击“捕捉 B”。",
  "B 포즈를 먼저 캡처하세요.": "请先捕捉 B 姿势。",
  "Block a two-shot": "摆一个双人镜头",
  "Browser-only copy": "仅保存在浏览器中的副本",
  "Building the ZIP. Cancel takes effect after the current work unit, before download.": "正在制作 ZIP。取消会在当前步骤结束后、下载开始前生效。",
  "Camera tutorial": "摄影机教程",
  "Cancel export": "取消导出",
  "Cancel stops at the next frame boundary, before download.": "取消会在下一帧边界生效，下载不会开始。",
  "Cancelling at the current work boundary…": "将在当前步骤结束后取消…",
  "Checking motion generation…": "正在检查动作生成…",
  "Checking…": "正在检查…",
  "Clay": "灰模",
  "Click here": "点击这里",
  "Click to fly the shot camera": "点击后操控镜头摄影机",
  "Close tutorial": "关闭教程",
  "Completed": "已完成",
  "Depth (mp4)": "深度视频（MP4）",
  "Depth pass of the whole shot as an mp4 for video-model conditioning": "将整段镜头的深度通道导出为 MP4，供视频模型条件控制使用",
  "Depth range sampled": "已采样深度范围",
  "Direct the scene": "指导场景",
  "Dolly": "推拉",
  "Done": "完成",
  "Download requested": "已请求下载",
  "Drag a line here": "在这里拖出一条线",
  "Edit properties": "编辑属性",
  "Encoding the requested frames, not yet a completed file.": "正在编码所选帧，文件尚未完成。",
  "Encoding": "编码中",
  "Everything you add to the set lives here. Pick one to edit it, or click it in the shot view. Drop a picture anywhere here — or on the shot view — to stand it up as a cutout. You can also drop a .glb, .obj or .fbx to import a 3D object.": "加入场景的物件都在这里。选中物件或在镜头视图中点击它即可编辑。把图片拖到这里或镜头视图可生成立牌；拖入 .glb、.obj 或 .fbx 可导入三维物件。",
  "Export cancelled. No further downloads will be requested.": "导出已取消，不会再请求下载。",
  "Export completed. Download requested; check your browser's downloads. The OS save is not confirmed.": "导出已完成并请求下载。请检查浏览器下载列表；系统保存结果尚未确认。",
  "Export could not finish. Retry the same request. For memory or resource problems, close other heavy tabs or use a shorter range / lower output resolution in a new export.": "导出未能完成。可以重试同一请求。若资源不足，请关闭其他占用资源的标签页，或缩短范围、降低分辨率后重新导出。",
  "Export pipeline completed. The requesting tool handles the file handoff.": "导出流程已完成，文件交接由调用工具处理。",
  "Exports: keyframe pack, video, passes, storyboard, cut list": "导出：关键帧包、视频、通道图、故事板、剪辑表",
  "External URL": "外部网址",
  "Fal motion reference poses": "Fal 动作参考姿势",
  "Fal 모션 방식": "Fal 动作模式",
  "Fal 모션 생성": "Fal 动作生成",
  "Fal 모션 생성은 QA 중 잠겨 있어요.": "Fal 动作生成在测试期间暂不可用。",
  "Fal 모션 진행 단계": "Fal 动作生成步骤",
  "fal 비율로 샷 시점": "将镜头设为 fal 比例",
  "Fal 생성에 실패했어요.": "Fal 生成失败。",
  "Finalizing MP4. Progress is indeterminate; this stage cannot be interrupted.": "正在完成 MP4；这一阶段无法估算进度，也无法中断。",
  "Finalizing": "收尾中",
  "Finishing encoder output. Progress is indeterminate.": "正在完成编码输出，暂时无法估算进度。",
  "Frame download requested. Check your browser's downloads.": "已请求下载画面，请检查浏览器下载列表。",
  "Frame rendering failed. Let the scene finish loading, then retry. If it repeats, shorten the range or reduce output resolution for a new export.": "画面渲染失败。请等场景加载完再试；若反复发生，请缩短导出范围或降低分辨率。",
  "Frame the selected character": "给选中人物构图",
  "Frames submitted to encoder": "已提交编码的帧",
  "Generate motion": "生成动作",
  "Generating motion…": "正在生成动作…",
  "GVHMR extraction is unavailable until the local GPU bridge is connected.": "连接本地 GPU 桥接服务后才能使用 GVHMR 动作提取。",
  "GVHMR extraction runs on the GPU box (about a minute per 15 s of footage).": "GVHMR 在 GPU 机器上提取动作（每 15 秒素材约需 1 分钟）。",
  "Handing off existing PNGs. Synchronous downloads cannot be cancelled.": "正在交付已有 PNG；同步下载无法取消。",
  "Height (m)": "高度（米）",
  "Hide": "隐藏",
  "Hold right, press keys": "按住右键并按方向键",
  "Import 3D object": "导入三维物件",
  "In project file": "已包含在工程文件中",
  "Keep this tab open. After restarting the bridge on the same port, retry the connection below.": "请保持此标签页打开。桥接服务在同一端口重启后，再点击下方重新连接。",
  "Keyframe pack (zip)": "关键帧包（ZIP）",
  "Kimodo setup and route guide": "Kimodo 安装与连接指南",
  "Light the set warmer": "让场景灯光更暖",
  "Load a rig to edit poses": "载入骨架后才能编辑姿势",
  "Local MLX/cpp supports one unconstrained prompt. Sequencing, pinned poses, paths and preserve need the CUDA/SSH route. Line editing needs a configured ProjFlow route.": "本地 MLX/cpp 只支持单段自由提示；多段动作、固定姿势、路径和局部保留需要 CUDA/SSH 路线。轨迹编辑还需要配置 ProjFlow。",
  "Look through the shot camera — right-drag, WASD and orbit set the recording lens (Esc returns)": "透过镜头摄影机查看；右键拖动、WASD 和环绕操作会调整录制机位（按 Esc 返回）",
  "Look through": "透过镜头查看",
  "Look": "环视",
  "Mesh": "网格模型",
  "Missing resources": "缺失的资源",
  "Missing": "缺失",
  "Model": "模型",
  "Motion generation complete": "动作生成完成",
  "Motion generation is optional. Sample motion, camera editing and exports work without it. Your scene and prompt blocks stay here while you set it up.": "动作生成是可选功能。预置动作、摄影机编辑和导出不依赖它；配置期间，场景和动作提示块会保留在这里。",
  "Motion generation setup": "动作生成设置",
  "MP4 encoding is unavailable. Use a current browser with H.264 WebCodecs support (such as Chrome or Edge), enable hardware acceleration, then retry.": "MP4 编码不可用。请使用支持 H.264 WebCodecs 的新版 Chrome 或 Edge，开启硬件加速后重试。",
  "My models": "我的模型",
  "New generation runs in the local Studio. Save your project here, then open that file in the local Studio to carry over your edits.": "新生成任务会在本地 Studio 中运行。请先保存工程，再在本地 Studio 打开该文件以继续编辑。",
  "Next · CozyClay motion source": "下一步 · CozyClay 动作源",
  "No AI video motion generations left today": "今天的 AI 视频动作生成次数已用完",
  "No imported models yet. Use “Import 3D object” in the Props inspector, or drop a .glb, .obj or .fbx into the studio.": "还没有导入模型。可在物件检查器中选择“导入三维物件”，或把 .glb、.obj、.fbx 文件拖进 Studio。",
  "No motion backend configured": "尚未配置动作后端",
  "Off": "关闭",
  "OK": "正常",
  "Open Export": "打开导出菜单",
  "Open Settings": "打开设置",
  "Orbit": "环绕",
  "OTIO cut list": "OTIO 剪辑表",
  "Panels": "面板",
  "Preparing the renderer and checking MP4 support…": "正在准备渲染器并检查 MP4 支持…",
  "Preparing": "准备中",
  "Project resources": "工程资源",
  "QA 잠금": "测试锁定",
  "Rail": "摄影机轨道",
  "Read the scene": "读取场景",
  "Ready for this motion request": "已准备好生成这段动作",
  "Recheck connection": "重新检查连接",
  "Reference grid": "参考网格",
  "Render the shot to an MP4 — camera move and character motion, no editor chrome": "将镜头导出为 MP4，包含摄影机与人物运动，不包含编辑器界面",
  "Retry connection": "重试连接",
  "Retry keeps the original shot, camera, range and settings; it does not change your edits.": "重试会沿用原镜头、摄影机、范围和设置，不会改动你的编辑。",
  "Retry same export": "重试本次导出",
  "Right-drag in the viewport to look around.": "在视口中按住右键拖动以环视。",
  "Right-drag to look": "右键拖动环视",
  "Run an editor action": "执行编辑器操作",
  "Scroll in the viewport to push in and pull out.": "在视口中滚动滚轮以推近或拉远。",
  "Scroll to push in": "滚轮推近",
  "Selection and view": "选中项与视图",
  "Show the agent chat column (Cmd/Ctrl+B)": "显示智能助手聊天栏（Cmd/Ctrl+B）",
  "Show": "显示",
  "Size": "大小",
  "Stage position — does not change the take": "场景位置，不改变动作片段",
  "Start from a scene": "从示例场景开始",
  "Storyboard (PNG)": "故事板（PNG）",
  "Switch route in Settings": "在设置中切换路线",
  "Take this shot with you. Its camera and range stay yours.": "把这个镜头带走；机位和时间范围都会保留。",
  "That is the whole camera: look, walk, dolly, orbit, cut, rail, play.": "这就是摄影机操作：环视、移动、推拉、环绕、剪切、轨道、播放。",
  "That model has no measurable geometry": "该模型没有可测量的几何体",
  "That model is no longer stored": "该模型已不在存储中",
  "That starter scene is not in this build": "当前版本没有这个示例场景",
  "The fixed-camera H3 Max Turbo video is attached to the extraction panel as a motion source. Run GVHMR there, then review the resulting take in the timeline.": "固定机位生成的 H3 Max Turbo 视频已作为动作源加入提取面板。在那里运行 GVHMR，再到时间轴检查生成的动作片段。",
  "The live editor is disconnected. Reconnect before sending.": "实时编辑器已断开，请重新连接后再发送。",
  "The motion backend is unavailable": "动作后端不可用",
  "The project file would be too large.": "工程文件会过大。",
  "This route cannot run the selected motion request": "当前路线无法处理所选动作请求",
  "Undo an edit": "撤销编辑",
  "Unknown reason": "未知原因",
  "Untitled model": "未命名模型",
  "Untitled Scene": "未命名场景",
  "Use an existing Kimodo host, then restart your local launcher with:": "使用已有的 Kimodo 主机，并用以下命令重启本地启动器：",
  "Use this video for mocap extraction": "用此视频提取动作",
  "Verify the result": "核对结果",
  "Video (mp4)": "视频（MP4）",
  "Video encoding failed. Retry the same request. If resources are tight, shorten the shot range or lower output resolution before starting a new export.": "视频编码失败。请重试；若资源不足，可缩短镜头范围或降低导出分辨率。",
  "View": "视图",
  "Viewport display toggles": "视口显示开关",
  "Viewport display": "视口显示",
  "Walk": "移动",
  "Workflow output": "工作流输出",
  "Your motion is ready": "动作已生成",
  "길이": "时长",
  "닫기": "关闭",
  "동작 생성": "生成动作",
  "동작 설명 · 생성": "动作描述 · 生成",
  "동작 설명을 입력하세요.": "请输入动作描述。",
  "렌더러가 준비되지 않았어요.": "渲染器尚未准备好。",
  "모캡 품질 게이트 통과": "动捕质量检查通过",
  "미캡처": "未捕捉",
  "보낼 프롬프트": "待发送提示词",
  "비워 두면 위 설명으로 자동 생성됩니다. 직접 고치면 그대로 전송됩니다.": "留空时根据上方描述自动生成；手动修改后会原样发送。",
  "색 세그멘테이션 음영 모드 ON · A/B 캡처 가능": "颜色分割明暗模式已开启 · 可捕捉 A/B",
  "색 세그멘테이션이 포함된 음영 A/B 참조를 다시 캡처하세요.": "请重新捕捉含颜色分割信息的明暗 A/B 参考。",
  "생성 작업 ID를 받지 못했어요.": "未收到生成任务 ID。",
  "생성 중…": "生成中…",
  "생성": "生成",
  "샷 시점을 H3 비율(832×480)로 맞추고 구도를 잡으세요.": "请将镜头设为 H3 的 832×480 比例并调整构图。",
  "소유자 테스트가 끝날 때까지 생성 요청은 서버에서 차단됩니다.": "所有者测试完成前，服务器会阻止生成请求。",
  "소유자 테스트가 끝날 때까지 잠겨 있습니다.": "所有者测试完成前暂不可用。",
  "완료": "完成",
  "음영 모드 켜기": "开启明暗模式",
  "음영": "明暗",
  "전신 프레임을 확인할 수 없어 참조를 캡처할 수 없어요. 잠시 후 다시 시도하세요.": "还无法确认全身是否入镜，请稍后再捕捉参考。",
  "초": "秒",
  "초기화": "重置",
  "카메라 잠그기": "锁定摄影机",
  "카메라 잠금 해제": "解锁摄影机",
  "카메라 잠금 해제됨 · A를 다시 캡처하면 새 기준을 저장합니다.": "摄影机已解锁 · 重新捕捉 A 会保存新的基准。",
  "캡처 완료": "已捕捉",
  "현재 프레임에서 A 캡처를 누르세요": "请在当前帧点击“捕捉 A”。",
  "확인 필요": "需要确认",
});
